### ISSUE TITLE
Running pyhttptest fails on Windows with ijson 2.5.1

### ISSUE THREAD

**Issue by plindman** [slaily/pyhttptest#2]
Running pyhttptest version 0.5 on Win10 with Python3.8 in virtualenv fails with error message:
ImportError: cannot import name '_yajl2' from 'ijson.backends' (.venv\lib\site-packages\ijson\backends\__init__.py)

After modifying the ijson dependency in '.venv/lib/site-packages/pyhttptest-0.5.dist.info/METADATA' from 2.5.1 to 3.0.1 and re-installing ijson==3.0.1, pyhttptest runs without errors.

```
Traceback (most recent call last):
  File "Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File ".venv\Scripts\pyhttptest.exe\__main__.py", line 5, in <module>
  File ".venv\lib\site-packages\pyhttptest\cli.py", line 3, in <module>
    from pyhttptest.wrappers import execute_test_scenarios
  File ".venv\lib\site-packages\pyhttptest\wrappers.py", line 1, in <module>
    from pyhttptest import core
  File ".venv\lib\site-packages\pyhttptest\core.py", line 1, in <module>
    import ijson.backends.yajl2_c as ijson
  File ".venv\lib\site-packages\ijson\backends\yajl2_c.py", line 14, in <module>
    from . import _yajl2 # @UnresolvedImport
ImportError: cannot import name '_yajl2' from 'ijson.backends' (.venv\lib\site-packages\ijson\backends\__init__.py)
```

**Comment by slaily** [comment]
Thank you for the report! I definitely will check it.

**Comment by frknycbs** [comment]
Hi @slaily @plindman 
I am getting same error on Ubuntu 20.04.1 LTS

root@furkan-VirtualBox:/home/furkan/Desktop/pyhttptest# pyhttptest execute deneme.json 
Traceback (most recent call last):
  File "/usr/local/bin/pyhttptest", line 5, in <module>
    from pyhttptest.cli import main
  File "/usr/local/lib/python3.8/dist-packages/pyhttptest/cli.py", line 3, in <module>
    from pyhttptest.wrappers import execute_test_scenarios
  File "/usr/local/lib/python3.8/dist-packages/pyhttptest/wrappers.py", line 1, in <module>
    from pyhttptest import core
  File "/usr/local/lib/python3.8/dist-packages/pyhttptest/core.py", line 1, in <module>
    import ijson.backends.yajl2_c as ijson
  File "/usr/local/lib/python3.8/dist-packages/ijson/backends/yajl2_c.py", line 14, in <module>
    from . import _yajl2 # @UnresolvedImport
ImportError: cannot import name '_yajl2' from 'ijson.backends' (/usr/local/lib/python3.8/dist-packages/ijson/backends/__init__.py)
